'use strict';

/**
 * src/routes/reports.js
 *
 * PDF Report Generation — Pro+ feature (requirePlan('reportingDownload'))
 *
 * GET /reports/pdf?startDate=YYYY-MM-DD&endDate=YYYY-MM-DD&sections=cover,overview,...
 *
 * Generates a multi-page A4 PDF with:
 *   1. Cover Page
 *   2. Overview (KPI summary + campaign type breakdown)
 *   3. Advertising Overview (SP/SB/SD/DSP aggregate)
 *   4. Sponsored Products (top 20 campaigns)
 *   5. Sponsored Brands (top 20 campaigns)
 *   6. Sponsored Display (top 20 campaigns)
 *   7. DSP (top 20 campaigns)
 *   8. Budget Pacing
 *   9. Vendor Sales
 *  10. Seller Sales
 *  11. Inventory
 *  12. Forecasting
 */

const express    = require('express');
const router     = express.Router();
const PDFDocument = require('pdfkit');
const https      = require('https');
const http       = require('http');
const { requireAuth } = require('../middleware/requireAuth');
const { requirePlan } = require('../middleware/requirePlan');
const { query }  = require('../services/snowflakeService');
const { resolveClientId } = require('../services/advertiserResolver');

// ─── Color palette ────────────────────────────────────────────────────────────
const COLOR = {
  accent:  '#4F6EF7',   // Calbridge blue
  text:    '#1A1D2E',   // dark text
  muted:   '#6B7280',   // secondary text
  border:  '#E5E7EB',   // table borders
  surface: '#F9FAFB',   // alternating row bg
  white:   '#FFFFFF',
  danger:  '#EF4444',
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** ISO date validation */
const ISO_RE = /^\d{4}-\d{2}-\d{2}$/;

/**
 * Date filter SQL fragment — exact range when both dates provided, else rolling window.
 */
function dateFilter(col, days, startDate, endDate) {
  if (startDate && endDate && ISO_RE.test(startDate) && ISO_RE.test(endDate)) {
    return `AND ${col} BETWEEN '${startDate}' AND '${endDate}'`;
  }
  return `AND ${col} >= DATEADD(day, -${Number(days)}, CURRENT_DATE)`;
}

/** Safe number */
function n(v) { return v == null ? 0 : Number(v); }

/** Format currency */
function fmt$(v) { return '$' + n(v).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }

/** Format percent (ratio 0-1) */
function fmtPct(v) { return v == null ? '—' : (n(v) * 100).toFixed(1) + '%'; }

/** Format ROAS */
function fmtROAS(v) { return v == null ? '—' : n(v).toFixed(2) + 'x'; }

/** Truncate string with ellipsis */
function trunc(str, maxLen) {
  if (!str) return '';
  return String(str).length > maxLen ? String(str).substring(0, maxLen - 1) + '…' : String(str);
}

/**
 * Download image from URL into a Buffer.
 * Returns null if the URL is invalid, relative, or unreachable.
 */
function fetchImageBuffer(url) {
  return new Promise((resolve) => {
    if (!url || typeof url !== 'string') return resolve(null);
    if (url.startsWith('/') || (!url.startsWith('http://') && !url.startsWith('https://'))) {
      return resolve(null); // skip relative URLs — not embeddable in PDF
    }
    try {
      const lib = url.startsWith('https') ? https : http;
      const req = lib.get(url, { timeout: 5000 }, (res) => {
        if (res.statusCode < 200 || res.statusCode >= 300) return resolve(null);
        const chunks = [];
        res.on('data', c => chunks.push(c));
        res.on('end', () => resolve(Buffer.concat(chunks)));
        res.on('error', () => resolve(null));
      });
      req.on('error', () => resolve(null));
      req.on('timeout', () => { req.destroy(); resolve(null); });
    } catch { resolve(null); }
  });
}

// ─── PDF Layout helpers ───────────────────────────────────────────────────────
const PAGE_W  = 595.28;  // A4 width  (points)
const PAGE_H  = 841.89;  // A4 height (points)
const MARGIN  = 50;
const CONTENT_W = PAGE_W - MARGIN * 2;

/**
 * Draw the accent-coloured page header bar and return the Y cursor after it.
 */
function drawPageHeader(doc, title, dateRangeLabel, clientLogoBuffer, pageNum, totalPages) {
  const barH = 42;
  doc.rect(0, 0, PAGE_W, barH).fill(COLOR.accent);

  // Section title (left, white)
  doc.fillColor(COLOR.white)
     .fontSize(14)
     .font('Helvetica-Bold')
     .text(title, MARGIN, 13, { lineBreak: false });

  // Date range (right, white, smaller)
  doc.fontSize(9)
     .font('Helvetica')
     .text(dateRangeLabel, PAGE_W - MARGIN - 160, 16, { width: 155, align: 'right', lineBreak: false });

  // Client logo — top right within bar (if available)
  if (clientLogoBuffer) {
    try {
      doc.image(clientLogoBuffer, PAGE_W - MARGIN - 60, 6, { height: 30, fit: [60, 30] });
    } catch { /* skip bad image */ }
  }

  return barH + 12; // Y cursor after header + small gap
}

/**
 * Draw page footer: "Generated by Calbridge · Page N of M" centred,
 * agency logo bottom-right (if available).
 */
function drawPageFooter(doc, pageNum, totalPages, agencyLogoBuffer) {
  const footerY = PAGE_H - 30;
  doc.fillColor(COLOR.muted)
     .fontSize(8)
     .font('Helvetica')
     .text(`Generated by Calbridge · Page ${pageNum} of ${totalPages}`, MARGIN, footerY, {
       width: CONTENT_W,
       align: 'center',
       lineBreak: false,
     });

  if (agencyLogoBuffer) {
    try {
      doc.image(agencyLogoBuffer, PAGE_W - MARGIN - 55, footerY - 18, { height: 22, fit: [55, 22] });
    } catch { /* skip */ }
  }
}

/**
 * Draw a summary metric row: up to 4 KPI boxes side by side.
 * metrics = [{ label, value }]
 * Returns Y cursor after the row.
 */
function drawMetricRow(doc, metrics, y) {
  const count = Math.min(metrics.length, 4);
  const boxW  = CONTENT_W / count;
  const boxH  = 52;

  metrics.slice(0, count).forEach((m, i) => {
    const x = MARGIN + i * boxW;
    doc.rect(x, y, boxW - 4, boxH).fill(COLOR.surface);
    doc.fillColor(COLOR.muted).fontSize(9).font('Helvetica')
       .text(m.label, x + 8, y + 8, { width: boxW - 16, lineBreak: false });
    doc.fillColor(COLOR.text).fontSize(16).font('Helvetica-Bold')
       .text(m.value, x + 8, y + 22, { width: boxW - 16, lineBreak: false });
  });

  return y + boxH + 12;
}

/**
 * Draw a data table.
 * headers: [{ label, width, numeric? }]
 * rows:    array of arrays (strings / numbers — already formatted)
 * Returns Y cursor after the table (or PAGE_H-60 if truncated by page end).
 */
function drawTable(doc, headers, rows, startY) {
  const rowH       = 16;
  const headerH    = 18;
  const totalWidth = headers.reduce((s, h) => s + h.width, 0);
  let y = startY;

  // Header row background
  doc.rect(MARGIN, y, totalWidth, headerH).fill(COLOR.accent);

  // Header labels
  let xCur = MARGIN;
  headers.forEach(h => {
    doc.fillColor(COLOR.white)
       .fontSize(8)
       .font('Helvetica-Bold')
       .text(trunc(h.label, 30), xCur + 4, y + 5, {
         width: h.width - 8,
         align: h.numeric ? 'right' : 'left',
         lineBreak: false,
       });
    xCur += h.width;
  });
  y += headerH;

  // Data rows
  const maxRows = Math.floor((PAGE_H - 80 - y) / rowH);
  const visibleRows = rows.slice(0, maxRows);

  visibleRows.forEach((row, ri) => {
    const bg = ri % 2 === 0 ? COLOR.white : COLOR.surface;
    doc.rect(MARGIN, y, totalWidth, rowH).fill(bg);

    xCur = MARGIN;
    headers.forEach((h, ci) => {
      const cell = row[ci] != null ? String(row[ci]) : '—';
      doc.fillColor(COLOR.text)
         .fontSize(7.5)
         .font('Helvetica')
         .text(trunc(cell, h.numeric ? 20 : 40), xCur + 4, y + 4, {
           width: h.width - 8,
           align: h.numeric ? 'right' : 'left',
           lineBreak: false,
         });
      xCur += h.width;
    });

    // Row border
    doc.moveTo(MARGIN, y + rowH).lineTo(MARGIN + totalWidth, y + rowH)
       .strokeColor(COLOR.border).lineWidth(0.5).stroke();

    y += rowH;
  });

  if (rows.length > maxRows) {
    doc.fillColor(COLOR.muted).fontSize(8).font('Helvetica')
       .text(`(${rows.length - maxRows} more rows not shown)`, MARGIN, y + 4);
    y += 14;
  }

  return y + 4;
}

// ─── Route ───────────────────────────────────────────────────────────────────

router.get('/pdf', requireAuth, requirePlan('reportingDownload'), async (req, res, next) => {
  try {
    const clientId = await resolveClientId(req);

    // ── Date range ─────────────────────────────────────────────────────────
    let { startDate, endDate } = req.query;
    if (!startDate || !ISO_RE.test(startDate) || !endDate || !ISO_RE.test(endDate)) {
      // Default: last 30 days
      const now   = new Date();
      endDate     = now.toISOString().substring(0, 10);
      const start = new Date(now); start.setDate(start.getDate() - 30);
      startDate   = start.toISOString().substring(0, 10);
    }
    const days = 30; // fallback for non-date filter helpers
    const dateRangeLabel = `${startDate} → ${endDate}`;

    // ── Section filter ─────────────────────────────────────────────────────
    const ALL_SECTIONS = ['cover','overview','adoverview','sp','sb','sd','dsp','pacing','vendor','seller','inventory','forecasting'];
    const requestedSections = req.query.sections
      ? req.query.sections.split(',').map(s => s.trim().toLowerCase())
      : ALL_SECTIONS;
    const includeSection = s => requestedSections.includes(s);

    // ── Fetch logos ─────────────────────────────────────────────────────────
    const [clientRow, managerRow] = await Promise.all([
      query(`SELECT name, company_name, logo_url FROM CALBRIDGE_PROD.APP.clients WHERE client_id = ?`, [clientId])
        .catch(() => []),
      query(`
        SELECT ma.logo_url AS manager_logo
        FROM CALBRIDGE_PROD.APP.client_migration_map cm
        JOIN CALBRIDGE_PROD.APP.manager_accounts ma ON ma.manager_id = cm.manager_id
        WHERE cm.client_id = ?
        LIMIT 1
      `, [clientId]).catch(() => []),
    ]);

    const clientName      = clientRow[0]?.COMPANY_NAME || clientRow[0]?.company_name || clientRow[0]?.NAME || clientRow[0]?.name || 'Client';
    const clientLogoUrl   = clientRow[0]?.LOGO_URL    || clientRow[0]?.logo_url   || null;
    const agencyLogoUrl   = managerRow[0]?.MANAGER_LOGO || managerRow[0]?.manager_logo || null;

    const [clientLogoBuffer, agencyLogoBuffer] = await Promise.all([
      fetchImageBuffer(clientLogoUrl),
      fetchImageBuffer(agencyLogoUrl),
    ]);

    // ── Fetch all section data in parallel ─────────────────────────────────
    const df = (col) => dateFilter(col, days, startDate, endDate);

    const [
      overviewRow,
      adTypeRows,
      spCampaigns,
      sbCampaigns,
      sdCampaigns,
      dspCampaigns,
      pacingRows,
      vendorRow,
      vendorAsins,
      sellerRow,
      sellerAsins,
      inventoryRows,
      forecastRows,
    ] = await Promise.all([

      // 1. Overview: blended KPIs from mart_advertising_daily
      query(`
        SELECT
          SUM(spend)       AS total_spend,
          SUM(sales)       AS total_sales,
          SUM(impressions) AS total_impressions,
          SUM(clicks)      AS total_clicks,
          SUM(orders)      AS total_orders,
          CASE WHEN SUM(sales)  > 0 THEN SUM(spend) / SUM(sales)  ELSE NULL END AS acos,
          CASE WHEN SUM(spend)  > 0 THEN SUM(sales) / SUM(spend)  ELSE NULL END AS roas
        FROM CALBRIDGE_PROD.MARTS_MARTS.mart_advertising_daily
        WHERE client_id = ?
          AND COALESCE(marketplace, 'US') = 'US'
          ${df('date')}
      `, [clientId]).catch(() => [{}]),

      // 2. Advertising Overview: by ad_type
      query(`
        SELECT
          ad_type,
          SUM(spend)       AS spend,
          SUM(sales)       AS sales,
          SUM(impressions) AS impressions,
          SUM(clicks)      AS clicks,
          SUM(orders)      AS orders,
          CASE WHEN SUM(sales) > 0 THEN SUM(spend) / SUM(sales) ELSE NULL END AS acos,
          CASE WHEN SUM(spend) > 0 THEN SUM(sales) / SUM(spend) ELSE NULL END AS roas
        FROM CALBRIDGE_PROD.MARTS_MARTS.mart_advertising_daily
        WHERE client_id = ?
          AND COALESCE(marketplace, 'US') = 'US'
          ${df('date')}
        GROUP BY ad_type
        ORDER BY spend DESC
      `, [clientId]).catch(() => []),

      // 3. SP top 20 campaigns
      query(`
        SELECT campaign_name, SUM(impressions) AS impressions, SUM(clicks) AS clicks,
               SUM(adjusted_spend) AS spend, SUM(sales) AS sales,
               CASE WHEN SUM(clicks) > 0 THEN SUM(clicks)::FLOAT / NULLIF(SUM(impressions),0) ELSE NULL END AS ctr,
               CASE WHEN SUM(sales) > 0 THEN SUM(adjusted_spend) / SUM(sales) ELSE NULL END AS acos,
               CASE WHEN SUM(adjusted_spend) > 0 THEN SUM(sales) / SUM(adjusted_spend) ELSE NULL END AS roas
        FROM CALBRIDGE_PROD.APP.ADJUSTED_CAMPAIGN_PERFORMANCE
        WHERE client_id = ? AND ad_type = 'SP'
          AND COALESCE(marketplace,'US') = 'US'
          ${df('date')}
        GROUP BY campaign_name ORDER BY spend DESC NULLS LAST LIMIT 20
      `, [clientId]).catch(() => []),

      // 4. SB top 20 campaigns
      query(`
        SELECT campaign_name, SUM(impressions) AS impressions, SUM(clicks) AS clicks,
               SUM(adjusted_spend) AS spend, SUM(sales) AS sales,
               CASE WHEN SUM(clicks) > 0 THEN SUM(clicks)::FLOAT / NULLIF(SUM(impressions),0) ELSE NULL END AS ctr,
               CASE WHEN SUM(sales) > 0 THEN SUM(adjusted_spend) / SUM(sales) ELSE NULL END AS acos,
               CASE WHEN SUM(adjusted_spend) > 0 THEN SUM(sales) / SUM(adjusted_spend) ELSE NULL END AS roas
        FROM CALBRIDGE_PROD.APP.ADJUSTED_CAMPAIGN_PERFORMANCE
        WHERE client_id = ? AND ad_type = 'SB'
          AND COALESCE(marketplace,'US') = 'US'
          ${df('date')}
        GROUP BY campaign_name ORDER BY spend DESC NULLS LAST LIMIT 20
      `, [clientId]).catch(() => []),

      // 5. SD top 20 campaigns
      query(`
        SELECT campaign_name, SUM(impressions) AS impressions, SUM(clicks) AS clicks,
               SUM(adjusted_spend) AS spend, SUM(sales) AS sales,
               CASE WHEN SUM(clicks) > 0 THEN SUM(clicks)::FLOAT / NULLIF(SUM(impressions),0) ELSE NULL END AS ctr,
               CASE WHEN SUM(sales) > 0 THEN SUM(adjusted_spend) / SUM(sales) ELSE NULL END AS acos,
               CASE WHEN SUM(adjusted_spend) > 0 THEN SUM(sales) / SUM(adjusted_spend) ELSE NULL END AS roas
        FROM CALBRIDGE_PROD.APP.ADJUSTED_CAMPAIGN_PERFORMANCE
        WHERE client_id = ? AND ad_type = 'SD'
          AND COALESCE(marketplace,'US') = 'US'
          ${df('date')}
        GROUP BY campaign_name ORDER BY spend DESC NULLS LAST LIMIT 20
      `, [clientId]).catch(() => []),

      // 6. DSP top 20 campaigns
      query(`
        SELECT campaign_name, SUM(impressions) AS impressions, SUM(clicks) AS clicks,
               SUM(adjusted_spend) AS spend, SUM(sales) AS sales,
               CASE WHEN SUM(clicks) > 0 THEN SUM(clicks)::FLOAT / NULLIF(SUM(impressions),0) ELSE NULL END AS ctr,
               CASE WHEN SUM(sales) > 0 THEN SUM(adjusted_spend) / SUM(sales) ELSE NULL END AS acos,
               CASE WHEN SUM(adjusted_spend) > 0 THEN SUM(sales) / SUM(adjusted_spend) ELSE NULL END AS roas
        FROM CALBRIDGE_PROD.APP.ADJUSTED_CAMPAIGN_PERFORMANCE
        WHERE client_id = ? AND ad_type = 'DSP'
          AND COALESCE(marketplace,'US') = 'US'
          ${df('date')}
        GROUP BY campaign_name ORDER BY spend DESC NULLS LAST LIMIT 20
      `, [clientId]).catch(() => []),

      // 7. Budget Pacing (current month)
      query(`
        SELECT
          COALESCE(c.campaign_name, MAX(r.campaign_name)) AS campaign_name,
          COALESCE(c.campaign_type, r.ad_type)            AS campaign_type,
          c.budget                                        AS daily_budget,
          COALESCE(SUM(r.adjusted_spend), 0)              AS mtd_spend,
          CASE WHEN c.budget IS NOT NULL AND c.budget > 0
            THEN c.budget * DAY(LAST_DAY(CURRENT_DATE))
            ELSE NULL END                                 AS monthly_budget,
          CASE WHEN c.budget IS NOT NULL AND c.budget > 0
            THEN (c.budget * DAY(LAST_DAY(CURRENT_DATE))) * (DAY(CURRENT_DATE) / DAY(LAST_DAY(CURRENT_DATE))::FLOAT)
            ELSE NULL END                                 AS expected_mtd,
          CASE WHEN c.budget IS NOT NULL AND c.budget > 0 AND DAY(CURRENT_DATE) > 0
            THEN (SUM(r.adjusted_spend) / DAY(CURRENT_DATE)) * DAY(LAST_DAY(CURRENT_DATE))
            ELSE NULL END                                 AS projected_eom
        FROM CALBRIDGE_PROD.APP.ADJUSTED_CAMPAIGN_PERFORMANCE r
        LEFT JOIN CALBRIDGE_PROD.APP.AD_CAMPAIGNS c
          ON c.client_id = r.client_id AND c.campaign_id = r.campaign_id
        WHERE r.client_id = ?
          AND COALESCE(r.marketplace,'US') = 'US'
          AND r.date >= DATE_TRUNC('month', CURRENT_DATE)
        GROUP BY r.campaign_id, r.ad_type, c.campaign_name, c.campaign_type, c.budget
        ORDER BY mtd_spend DESC
      `, [clientId]).catch(() => []),

      // 8a. Vendor Sales KPIs
      query(`
        SELECT
          SUM(ordered_revenue)  AS ordered_revenue,
          SUM(shipped_revenue)  AS shipped_revenue,
          SUM(ordered_units)    AS ordered_units,
          SUM(shipped_units)    AS shipped_units
        FROM CALBRIDGE_PROD.APP.VENDOR_SALES
        WHERE client_id = ?
          ${df('start_date')}
          AND start_date = end_date
      `, [clientId]).catch(() => [{}]),

      // 8b. Vendor top ASINs
      query(`
        SELECT vs.asin, MAX(p.title) AS title,
               SUM(vs.shipped_revenue) AS shipped_revenue,
               SUM(vs.ordered_revenue) AS ordered_revenue,
               SUM(vs.shipped_units)   AS shipped_units
        FROM CALBRIDGE_PROD.APP.VENDOR_SALES vs
        LEFT JOIN CALBRIDGE_PROD.APP.PRODUCTS p ON p.client_id = vs.client_id AND p.asin = vs.asin
        WHERE vs.client_id = ?
          ${df('vs.start_date')}
          AND vs.start_date = vs.end_date
        GROUP BY vs.asin
        ORDER BY shipped_revenue DESC NULLS LAST
        LIMIT 10
      `, [clientId]).catch(() => []),

      // 9a. Seller Sales KPIs (account-level rows use asin = '__ACCOUNT__')
      query(`
        SELECT
          SUM(ordered_units)   AS ordered_units,
          SUM(ordered_revenue) AS ordered_revenue
        FROM CALBRIDGE_PROD.RAW.RETAIL_SALES_TRAFFIC
        WHERE client_id = ? AND asin = '__ACCOUNT__'
          ${df('date')}
      `, [clientId]).catch(() => [{}]),

      // 9b. Seller top ASINs
      query(`
        SELECT asin,
               SUM(ordered_units)   AS ordered_units,
               SUM(ordered_revenue) AS ordered_revenue
        FROM CALBRIDGE_PROD.RAW.RETAIL_SALES_TRAFFIC
        WHERE client_id = ? AND asin != '__ACCOUNT__'
          ${df('date')}
        GROUP BY asin
        ORDER BY ordered_revenue DESC NULLS LAST
        LIMIT 10
      `, [clientId]).catch(() => []),

      // 10. Inventory — top 20 ASINs by units on hand
      query(`
        SELECT asin,
               SUM(sellable_on_hand_units) AS sellable_units,
               SUM(open_po_units)          AS open_po_units,
               MIN(weeks_of_cover)         AS weeks_of_cover
        FROM CALBRIDGE_PROD.APP.VENDOR_INVENTORY
        WHERE client_id = ?
          AND start_date = (
            SELECT MAX(start_date) FROM CALBRIDGE_PROD.APP.VENDOR_INVENTORY WHERE client_id = ?
          )
        GROUP BY asin
        ORDER BY sellable_units DESC NULLS LAST
        LIMIT 20
      `, [clientId, clientId]).catch(() => []),

      // 11. Forecasting — top 20 ASINs, next 4 weeks P70/P80/P90
      query(`
        SELECT f.asin, MAX(p.title) AS title,
               SUM(f.p70_forecast_units) AS p70,
               SUM(f.p80_forecast_units) AS p80,
               SUM(f.p90_forecast_units) AS p90,
               SUM(f.mean_forecast_units) AS mean_units
        FROM CALBRIDGE_PROD.APP.VENDOR_FORECASTS f
        LEFT JOIN CALBRIDGE_PROD.APP.PRODUCTS p ON p.client_id = f.client_id AND p.asin = f.asin
        WHERE f.client_id = ?
          AND f.start_date >= CURRENT_DATE
          AND f.start_date <= DATEADD('week', 4, CURRENT_DATE)
        GROUP BY f.asin
        ORDER BY mean_units DESC NULLS LAST
        LIMIT 20
      `, [clientId]).catch(() => []),
    ]);

    // ─── Build PDF ──────────────────────────────────────────────────────────
    const doc = new PDFDocument({ size: 'A4', margin: MARGIN, autoFirstPage: false });

    // Stream response
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="calbridge-report-${endDate}.pdf"`);
    doc.pipe(res);

    // Track pages for footer (we'll inject footer on each pageAdded event)
    let pageCount = 0;
    // Pre-count pages by planning which sections will render
    // We calculate total at the end — use a placeholder for now;
    // pdfkit doesn't support back-patching text easily, so we'll use "N" and finalize later.
    // Instead, track pages as we add them.
    const pages = []; // track (pageNum, sectionTitle) for accurate total

    function addPage() {
      doc.addPage({ size: 'A4', margin: MARGIN });
      pageCount++;
      pages.push(pageCount);
    }

    // Helpers using closure over pageCount
    function sectionHeader(title) {
      return drawPageHeader(doc, title, dateRangeLabel, clientLogoBuffer, pageCount, '?');
    }

    function footer() {
      drawPageFooter(doc, pageCount, '?', agencyLogoBuffer);
    }

    // ── 1. Cover Page ────────────────────────────────────────────────────────
    if (includeSection('cover')) {
      addPage();

      // Top brand bar (full height top half)
      const barH = PAGE_H * 0.45;
      doc.rect(0, 0, PAGE_W, barH).fill(COLOR.accent);

      // Title
      doc.fillColor(COLOR.white)
         .fontSize(34)
         .font('Helvetica-Bold')
         .text('Performance Report', MARGIN, barH * 0.30, { width: CONTENT_W });

      // Subtitle
      doc.fontSize(16)
         .font('Helvetica')
         .text(clientName, MARGIN, barH * 0.30 + 48);

      doc.fontSize(13)
         .text(dateRangeLabel, MARGIN, barH * 0.30 + 70);

      // Client logo — top right of bar
      if (clientLogoBuffer) {
        try { doc.image(clientLogoBuffer, PAGE_W - MARGIN - 90, 20, { fit: [90, 60] }); } catch {}
      }

      // Bottom half: meta info
      const bottomY = barH + 40;
      doc.fillColor(COLOR.text)
         .fontSize(11)
         .font('Helvetica')
         .text(`Generated: ${new Date().toUTCString()}`, MARGIN, bottomY);

      doc.fontSize(10)
         .fillColor(COLOR.muted)
         .text('This report was generated by Calbridge — Amazon Analytics & Advertising Intelligence.', MARGIN, bottomY + 20, { width: CONTENT_W * 0.65 });

      // Agency logo (bottom right)
      if (agencyLogoBuffer) {
        try { doc.image(agencyLogoBuffer, PAGE_W - MARGIN - 80, bottomY, { fit: [80, 50] }); } catch {}
      }
    }

    // ── 2. Overview ──────────────────────────────────────────────────────────
    if (includeSection('overview')) {
      addPage();
      const ov = overviewRow[0] || {};
      let y = sectionHeader('Overview');

      // KPI row
      const kpis = [
        { label: 'Total Ad Spend',  value: fmt$(ov.TOTAL_SPEND  || ov.total_spend)  },
        { label: 'Total Ad Sales',  value: fmt$(ov.TOTAL_SALES  || ov.total_sales)  },
        { label: 'Blended ROAS',    value: fmtROAS(ov.ROAS      || ov.roas)         },
        { label: 'Blended ACoS',    value: fmtPct(ov.ACOS       || ov.acos)         },
      ];
      y = drawMetricRow(doc, kpis, y);

      // Secondary KPIs row
      const kpis2 = [
        { label: 'Impressions', value: n(ov.TOTAL_IMPRESSIONS || ov.total_impressions).toLocaleString() },
        { label: 'Clicks',      value: n(ov.TOTAL_CLICKS     || ov.total_clicks).toLocaleString()      },
        { label: 'Orders',      value: n(ov.TOTAL_ORDERS     || ov.total_orders).toLocaleString()      },
        { label: 'Date Range',  value: dateRangeLabel },
      ];
      y = drawMetricRow(doc, kpis2, y);

      // Campaign type breakdown table
      if (adTypeRows.length > 0) {
        y += 8;
        doc.fillColor(COLOR.text).fontSize(10).font('Helvetica-Bold').text('By Campaign Type', MARGIN, y);
        y += 14;

        const headers = [
          { label: 'Type',        width: 70  },
          { label: 'Spend',       width: 85,  numeric: true },
          { label: 'Sales',       width: 85,  numeric: true },
          { label: 'ROAS',        width: 60,  numeric: true },
          { label: 'ACoS',        width: 60,  numeric: true },
          { label: 'Impressions', width: 90,  numeric: true },
          { label: 'Clicks',      width: 70,  numeric: true },
          { label: 'Orders',      width: 75,  numeric: true },
        ];

        const rows = adTypeRows.map(r => [
          r.AD_TYPE || r.ad_type || '—',
          fmt$(r.SPEND  || r.spend),
          fmt$(r.SALES  || r.sales),
          fmtROAS(r.ROAS || r.roas),
          fmtPct(r.ACOS  || r.acos),
          n(r.IMPRESSIONS || r.impressions).toLocaleString(),
          n(r.CLICKS      || r.clicks).toLocaleString(),
          n(r.ORDERS      || r.orders).toLocaleString(),
        ]);

        drawTable(doc, headers, rows, y);
      }

      footer();
    }

    // ── 3. Advertising Overview (same data, different framing) ────────────────
    if (includeSection('adoverview') && adTypeRows.length > 0) {
      addPage();
      let y = sectionHeader('Advertising Overview');

      // Total row from mart
      const ov = overviewRow[0] || {};
      const totalKpis = [
        { label: 'Total Spend', value: fmt$(ov.TOTAL_SPEND || ov.total_spend) },
        { label: 'Total Sales', value: fmt$(ov.TOTAL_SALES || ov.total_sales) },
        { label: 'ROAS',        value: fmtROAS(ov.ROAS     || ov.roas)        },
        { label: 'ACoS',        value: fmtPct(ov.ACOS      || ov.acos)        },
      ];
      y = drawMetricRow(doc, totalKpis, y);

      y += 8;
      doc.fillColor(COLOR.text).fontSize(10).font('Helvetica-Bold').text('Performance by Channel', MARGIN, y);
      y += 14;

      const headers = [
        { label: 'Channel',     width: 70  },
        { label: 'Spend',       width: 85,  numeric: true },
        { label: 'Sales',       width: 85,  numeric: true },
        { label: 'ROAS',        width: 60,  numeric: true },
        { label: 'ACoS',        width: 60,  numeric: true },
        { label: 'Impressions', width: 90,  numeric: true },
        { label: 'Clicks',      width: 70,  numeric: true },
        { label: 'Orders',      width: 75,  numeric: true },
      ];
      const rows = adTypeRows.map(r => [
        r.AD_TYPE || r.ad_type || '—',
        fmt$(r.SPEND  || r.spend),
        fmt$(r.SALES  || r.sales),
        fmtROAS(r.ROAS || r.roas),
        fmtPct(r.ACOS  || r.acos),
        n(r.IMPRESSIONS || r.impressions).toLocaleString(),
        n(r.CLICKS      || r.clicks).toLocaleString(),
        n(r.ORDERS      || r.orders).toLocaleString(),
      ]);

      drawTable(doc, headers, rows, y);
      footer();
    }

    // ── Helper: draw a campaigns page ─────────────────────────────────────────
    function drawCampaignPage(title, campaigns) {
      if (!campaigns || campaigns.length === 0) return;
      addPage();
      let y = sectionHeader(title);

      const totalSpend = campaigns.reduce((s, r) => s + n(r.SPEND || r.spend), 0);
      const totalSales = campaigns.reduce((s, r) => s + n(r.SALES || r.sales), 0);
      const kpis = [
        { label: 'Total Spend', value: fmt$(totalSpend) },
        { label: 'Total Sales', value: fmt$(totalSales) },
        { label: 'Blended ROAS', value: totalSpend > 0 ? (totalSales / totalSpend).toFixed(2) + 'x' : '—' },
        { label: 'Campaigns',   value: String(campaigns.length) },
      ];
      y = drawMetricRow(doc, kpis, y);

      const headers = [
        { label: 'Campaign Name', width: 185 },
        { label: 'Impressions',   width: 75,  numeric: true },
        { label: 'Clicks',        width: 55,  numeric: true },
        { label: 'CTR',           width: 45,  numeric: true },
        { label: 'Spend',         width: 70,  numeric: true },
        { label: 'Sales',         width: 70,  numeric: true },
        { label: 'ROAS',          width: 48,  numeric: true },
        { label: 'ACoS',          width: 48,  numeric: true },
      ];
      const rows = campaigns.map(r => [
        r.CAMPAIGN_NAME || r.campaign_name || '—',
        n(r.IMPRESSIONS || r.impressions).toLocaleString(),
        n(r.CLICKS      || r.clicks).toLocaleString(),
        fmtPct(r.CTR    || r.ctr),
        fmt$(r.SPEND    || r.spend),
        fmt$(r.SALES    || r.sales),
        fmtROAS(r.ROAS  || r.roas),
        fmtPct(r.ACOS   || r.acos),
      ]);

      drawTable(doc, headers, rows, y);
      footer();
    }

    // ── 4–7. Per-channel campaign pages ───────────────────────────────────────
    if (includeSection('sp'))  drawCampaignPage('Sponsored Products', spCampaigns);
    if (includeSection('sb'))  drawCampaignPage('Sponsored Brands',   sbCampaigns);
    if (includeSection('sd'))  drawCampaignPage('Sponsored Display',  sdCampaigns);
    if (includeSection('dsp')) drawCampaignPage('DSP',                dspCampaigns);

    // ── 8. Budget Pacing ──────────────────────────────────────────────────────
    if (includeSection('pacing') && pacingRows.length > 0) {
      addPage();
      let y = sectionHeader('Budget Pacing');

      const totalMtd = pacingRows.reduce((s, r) => s + n(r.MTD_SPEND || r.mtd_spend), 0);
      const totalBudget = pacingRows.reduce((s, r) => s + n(r.MONTHLY_BUDGET || r.monthly_budget), 0);
      const kpis = [
        { label: 'MTD Spend',         value: fmt$(totalMtd) },
        { label: 'Total Monthly Budget', value: totalBudget > 0 ? fmt$(totalBudget) : '—' },
        { label: 'Campaigns Tracked', value: String(pacingRows.length) },
        { label: 'Month',             value: new Date().toLocaleString('en-US', { month: 'long', year: 'numeric' }) },
      ];
      y = drawMetricRow(doc, kpis, y);

      const headers = [
        { label: 'Campaign',       width: 175 },
        { label: 'Type',           width: 50  },
        { label: 'Daily Budget',   width: 70,  numeric: true },
        { label: 'MTD Spend',      width: 70,  numeric: true },
        { label: 'Pacing %',       width: 55,  numeric: true },
        { label: 'Proj. EOM',      width: 75,  numeric: true },
      ];

      const rows = pacingRows.map(r => {
        const mtd      = n(r.MTD_SPEND    || r.mtd_spend);
        const expected = n(r.EXPECTED_MTD || r.expected_mtd);
        const pacingPct = expected > 0 ? ((mtd / expected) * 100).toFixed(1) + '%' : '—';
        return [
          r.CAMPAIGN_NAME || r.campaign_name || '—',
          r.CAMPAIGN_TYPE || r.campaign_type || '—',
          r.DAILY_BUDGET  || r.daily_budget ? fmt$(r.DAILY_BUDGET || r.daily_budget) : '—',
          fmt$(mtd),
          pacingPct,
          r.PROJECTED_EOM || r.projected_eom ? fmt$(r.PROJECTED_EOM || r.projected_eom) : '—',
        ];
      });

      drawTable(doc, headers, rows, y);
      footer();
    }

    // ── 9. Vendor Sales ───────────────────────────────────────────────────────
    if (includeSection('vendor')) {
      const vs = vendorRow[0] || {};
      const hasVendor = n(vs.ORDERED_REVENUE || vs.ordered_revenue) > 0 || n(vs.SHIPPED_REVENUE || vs.shipped_revenue) > 0;

      addPage();
      let y = sectionHeader('Vendor Sales');

      if (!hasVendor) {
        doc.fillColor(COLOR.muted).fontSize(11).font('Helvetica')
           .text('No Vendor Central data found for this date range. Connect your Vendor Central account to unlock vendor analytics.', MARGIN, y + 20, { width: CONTENT_W });
      } else {
        const kpis = [
          { label: 'Ordered Revenue',  value: fmt$(vs.ORDERED_REVENUE  || vs.ordered_revenue)  },
          { label: 'Shipped Revenue',  value: fmt$(vs.SHIPPED_REVENUE  || vs.shipped_revenue)  },
          { label: 'Ordered Units',    value: n(vs.ORDERED_UNITS  || vs.ordered_units).toLocaleString()  },
          { label: 'Shipped Units',    value: n(vs.SHIPPED_UNITS  || vs.shipped_units).toLocaleString()  },
        ];
        y = drawMetricRow(doc, kpis, y);

        if (vendorAsins.length > 0) {
          y += 8;
          doc.fillColor(COLOR.text).fontSize(10).font('Helvetica-Bold').text('Top 10 ASINs by Shipped Revenue', MARGIN, y);
          y += 14;

          const headers = [
            { label: 'ASIN',             width: 90  },
            { label: 'Title',            width: 200 },
            { label: 'Shipped Revenue',  width: 100, numeric: true },
            { label: 'Ordered Revenue',  width: 100, numeric: true },
            { label: 'Shipped Units',    width: 75,  numeric: true },
          ];
          const rows = vendorAsins.map(r => [
            r.ASIN || r.asin,
            r.TITLE || r.title || '—',
            fmt$(r.SHIPPED_REVENUE || r.shipped_revenue),
            fmt$(r.ORDERED_REVENUE || r.ordered_revenue),
            n(r.SHIPPED_UNITS || r.shipped_units).toLocaleString(),
          ]);
          drawTable(doc, headers, rows, y);
        }
      }
      footer();
    }

    // ── 10. Seller Sales ──────────────────────────────────────────────────────
    if (includeSection('seller')) {
      const ss = sellerRow[0] || {};
      const hasSeller = n(ss.ORDERED_REVENUE || ss.ordered_revenue) > 0;

      addPage();
      let y = sectionHeader('Seller Sales');

      if (!hasSeller) {
        doc.fillColor(COLOR.muted).fontSize(11).font('Helvetica')
           .text('No Seller Central data found for this date range. Connect your Seller Central account to unlock seller analytics.', MARGIN, y + 20, { width: CONTENT_W });
      } else {
        const kpis = [
          { label: 'Ordered Revenue', value: fmt$(ss.ORDERED_REVENUE || ss.ordered_revenue) },
          { label: 'Ordered Units',   value: n(ss.ORDERED_UNITS || ss.ordered_units).toLocaleString() },
          { label: 'Date Range',      value: dateRangeLabel },
          { label: 'Source',          value: 'Seller Central' },
        ];
        y = drawMetricRow(doc, kpis, y);

        if (sellerAsins.length > 0) {
          y += 8;
          doc.fillColor(COLOR.text).fontSize(10).font('Helvetica-Bold').text('Top 10 ASINs by Ordered Revenue', MARGIN, y);
          y += 14;

          const headers = [
            { label: 'ASIN',            width: 100 },
            { label: 'Ordered Revenue', width: 150, numeric: true },
            { label: 'Ordered Units',   width: 100, numeric: true },
          ];
          const rows = sellerAsins.map(r => [
            r.ASIN || r.asin,
            fmt$(r.ORDERED_REVENUE || r.ordered_revenue),
            n(r.ORDERED_UNITS || r.ordered_units).toLocaleString(),
          ]);
          drawTable(doc, headers, rows, y);
        }
      }
      footer();
    }

    // ── 11. Inventory ─────────────────────────────────────────────────────────
    if (includeSection('inventory') && inventoryRows.length > 0) {
      addPage();
      let y = sectionHeader('Inventory');

      const totalUnits = inventoryRows.reduce((s, r) => s + n(r.SELLABLE_UNITS || r.sellable_units), 0);
      const atRisk = inventoryRows.filter(r => {
        const woc = n(r.WEEKS_OF_COVER || r.weeks_of_cover);
        return woc > 0 && woc < 4.3; // < ~30 days
      }).length;

      const kpis = [
        { label: 'Total Sellable Units', value: totalUnits.toLocaleString() },
        { label: 'ASINs Tracked',        value: String(inventoryRows.length) },
        { label: 'Low Stock (< 30 days)', value: String(atRisk) },
        { label: 'Snapshot',             value: 'Latest available' },
      ];
      y = drawMetricRow(doc, kpis, y);

      const headers = [
        { label: 'ASIN',             width: 100 },
        { label: 'Sellable Units',   width: 90,  numeric: true },
        { label: 'Open PO Units',    width: 90,  numeric: true },
        { label: 'Weeks of Cover',   width: 90,  numeric: true },
        { label: 'Restock Alert',    width: 95  },
      ];
      const rows = inventoryRows.map(r => {
        const woc = n(r.WEEKS_OF_COVER || r.weeks_of_cover);
        const restockFlag = woc > 0 && woc < 4.3 ? '⚠ Restock Soon' : (woc === 0 ? '—' : '✓ OK');
        return [
          r.ASIN || r.asin,
          n(r.SELLABLE_UNITS || r.sellable_units).toLocaleString(),
          n(r.OPEN_PO_UNITS  || r.open_po_units).toLocaleString(),
          woc > 0 ? woc.toFixed(1) : '—',
          restockFlag,
        ];
      });

      drawTable(doc, headers, rows, y);
      footer();
    }

    // ── 12. Forecasting ───────────────────────────────────────────────────────
    if (includeSection('forecasting') && forecastRows.length > 0) {
      addPage();
      let y = sectionHeader('Demand Forecasting (Next 4 Weeks)');

      const kpis = [
        { label: 'ASINs with Forecast', value: String(forecastRows.length) },
        { label: 'Forecast Horizon',    value: '4 Weeks' },
        { label: 'Confidence Levels',   value: 'P70 / P80 / P90' },
        { label: 'Source',              value: 'Amazon Forecast' },
      ];
      y = drawMetricRow(doc, kpis, y);

      const headers = [
        { label: 'ASIN',    width: 90  },
        { label: 'Title',   width: 175 },
        { label: 'P70 Units', width: 80, numeric: true },
        { label: 'P80 Units', width: 80, numeric: true },
        { label: 'P90 Units', width: 80, numeric: true },
        { label: 'Mean Units', width: 80, numeric: true },
      ];
      const rows = forecastRows.map(r => [
        r.ASIN  || r.asin,
        r.TITLE || r.title || '—',
        n(r.P70 || r.p70).toLocaleString(),
        n(r.P80 || r.p80).toLocaleString(),
        n(r.P90 || r.p90).toLocaleString(),
        n(r.MEAN_UNITS || r.mean_units).toLocaleString(),
      ]);

      drawTable(doc, headers, rows, y);
      footer();
    }

    // ── Finalize ──────────────────────────────────────────────────────────────
    doc.end();

  } catch (err) {
    // If we haven't started streaming yet, send error JSON
    if (!res.headersSent) {
      next(err);
    } else {
      // PDF stream already started — can't send HTTP error, just end the stream
      console.error('[reports] PDF generation error mid-stream:', err.message);
      try { res.end(); } catch {}
    }
  }
});

module.exports = router;
