ALTER TABLE CALBRIDGE_PROD.APP.clients ADD COLUMN IF NOT EXISTS email_verification_token VARCHAR;
ALTER TABLE CALBRIDGE_PROD.APP.clients ADD COLUMN IF NOT EXISTS email_verification_expires_at TIMESTAMP_NTZ;
ALTER TABLE CALBRIDGE_PROD.APP.clients ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMP_NTZ;
