#!/usr/bin/env node
/**
 * Step 1: Add missing columns to RAW.AD_CAMPAIGN
 * Run once via: node scripts/migration_step1_alter_table.js
 */

const { query } = require('../src/services/snowflakeService');

const alters = [
  // profile_id
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS PROFILE_ID VARCHAR(64)`,
  // marketplace_id
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS MARKETPLACE_ID VARCHAR(20)`,
  // SP-specific
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS TOP_OF_SEARCH_IMPRESSION_SHARE FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS CAMPAIGN_BUDGET_CURRENCY_CODE VARCHAR(10)`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS CAMPAIGN_BUDGET_TYPE VARCHAR(20)`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS CAMPAIGN_BIDDING_STRATEGY VARCHAR(50)`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS PORTFOLIO_ID VARCHAR(64)`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS UNITS_SOLD_1D FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS UNITS_SOLD_7D FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS UNITS_SOLD_14D FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS UNITS_SOLD_30D FLOAT`,
  // SB-specific
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS NEW_TO_BRAND_PURCHASES FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS NEW_TO_BRAND_PURCHASES_CLICKS FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS NEW_TO_BRAND_SALES FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS NEW_TO_BRAND_UNITS_SOLD FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS DETAIL_PAGE_VIEWS FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS ADD_TO_CART FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS VIDEO_5S_VIEWS FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS VIDEO_25PCT_VIEWS FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS VIDEO_50PCT_VIEWS FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS VIDEO_75PCT_VIEWS FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS VIDEO_100PCT_VIEWS FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS VIDEO_UNMUTES FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS VIEWABILITY_RATE FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS TOP_OF_SEARCH_IMPRESSION_SHARE_SB FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS BRANDED_SEARCHES FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS BRAND_STORE_PAGE_VIEWS FLOAT`,
  // SD-specific
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS PURCHASES_PROMOTED FLOAT`,
  `ALTER TABLE CALBRIDGE_PROD.RAW.AD_CAMPAIGN ADD COLUMN IF NOT EXISTS SALES_PROMOTED FLOAT`,
];

(async () => {
  let ok = 0, fail = 0;
  for (const sql of alters) {
    const colMatch = sql.match(/ADD COLUMN IF NOT EXISTS (\w+)/);
    const colName = colMatch ? colMatch[1] : sql;
    try {
      await query(sql);
      console.log(`✅ ${colName}`);
      ok++;
    } catch (e) {
      console.error(`❌ ${colName}: ${e.message}`);
      fail++;
    }
  }
  console.log(`\nDone: ${ok} succeeded, ${fail} failed`);
  process.exit(fail > 0 ? 1 : 0);
})();
