-- ============================================================
-- Amazon Ads Schema — Full rebuild
-- Column order matches API response + REPORT_TYPES definitions
-- Run after clearing all existing report tables
-- ============================================================

-- ============================================================
-- SPONSORED PRODUCTS
-- ============================================================

CREATE TABLE IF NOT EXISTS sp_campaign_report (
  client_id                            VARCHAR(36)   NOT NULL,
  profile_id                           VARCHAR(36)   NOT NULL,
  campaign_id                          VARCHAR(64)   NOT NULL,
  date                                 DATE          NOT NULL,
  -- Campaign metadata
  campaign_name                        VARCHAR(512),
  campaign_status                      VARCHAR(32),
  campaign_budget_amount               FLOAT,
  campaign_budget_type                 VARCHAR(64),
  campaign_budget_currency_code        VARCHAR(8),
  campaign_rule_based_budget_amount    FLOAT,
  campaign_applicable_budget_rule_id   VARCHAR(128),
  campaign_applicable_budget_rule_name VARCHAR(512),
  campaign_bidding_strategy            VARCHAR(64),
  portfolio_id                         VARCHAR(64),
  top_of_search_impression_share       FLOAT,
  -- Performance
  impressions                          NUMBER,
  clicks                               NUMBER,
  cost                                 FLOAT,
  -- Purchases — all windows
  purchases_1_d                        NUMBER,
  purchases_7_d                        NUMBER,
  purchases_14_d                       NUMBER,
  purchases_30_d                       NUMBER,
  purchases_same_sku_1_d               NUMBER,
  purchases_same_sku_7_d               NUMBER,
  purchases_same_sku_14_d              NUMBER,
  purchases_same_sku_30_d              NUMBER,
  -- Units sold — all windows
  units_sold_clicks_1_d                NUMBER,
  units_sold_clicks_7_d                NUMBER,
  units_sold_clicks_14_d               NUMBER,
  units_sold_clicks_30_d               NUMBER,
  units_sold_same_sku_1_d              NUMBER,
  units_sold_same_sku_7_d              NUMBER,
  units_sold_same_sku_14_d             NUMBER,
  units_sold_same_sku_30_d             NUMBER,
  -- Sales — all windows
  sales_1_d                            FLOAT,
  sales_7_d                            FLOAT,
  sales_14_d                           FLOAT,
  sales_30_d                           FLOAT,
  attributed_sales_same_sku_1_d        FLOAT,
  attributed_sales_same_sku_7_d        FLOAT,
  attributed_sales_same_sku_14_d       FLOAT,
  attributed_sales_same_sku_30_d       FLOAT,
  -- Misc
  kindle_edition_normalized_pages_read_14_d       NUMBER,
  kindle_edition_normalized_pages_royalties_14_d  FLOAT,
  add_to_list                          NUMBER,
  qualified_borrows                    NUMBER,
  royalty_qualified_borrows            NUMBER,
  synced_at                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id, profile_id, campaign_id, date)
);

CREATE TABLE IF NOT EXISTS sp_ad_group_report (
  client_id                            VARCHAR(36)   NOT NULL,
  profile_id                           VARCHAR(36)   NOT NULL,
  ad_group_id                          VARCHAR(64)   NOT NULL,
  date                                 DATE          NOT NULL,
  -- Ad group metadata
  ad_group_name                        VARCHAR(512),
  ad_status                            VARCHAR(32),
  -- Campaign context
  campaign_id                          VARCHAR(64),
  campaign_name                        VARCHAR(512),
  campaign_status                      VARCHAR(32),
  campaign_budget_amount               FLOAT,
  campaign_budget_type                 VARCHAR(64),
  campaign_budget_currency_code        VARCHAR(8),
  campaign_bidding_strategy            VARCHAR(64),
  portfolio_id                         VARCHAR(64),
  -- Performance
  impressions                          NUMBER,
  clicks                               NUMBER,
  cost                                 FLOAT,
  -- Purchases — all windows
  purchases_1_d                        NUMBER,
  purchases_7_d                        NUMBER,
  purchases_14_d                       NUMBER,
  purchases_30_d                       NUMBER,
  purchases_same_sku_1_d               NUMBER,
  purchases_same_sku_7_d               NUMBER,
  purchases_same_sku_14_d              NUMBER,
  purchases_same_sku_30_d              NUMBER,
  -- Units sold — all windows
  units_sold_clicks_1_d                NUMBER,
  units_sold_clicks_7_d                NUMBER,
  units_sold_clicks_14_d               NUMBER,
  units_sold_clicks_30_d               NUMBER,
  units_sold_same_sku_1_d              NUMBER,
  units_sold_same_sku_7_d              NUMBER,
  units_sold_same_sku_14_d             NUMBER,
  units_sold_same_sku_30_d             NUMBER,
  -- Sales — all windows
  sales_1_d                            FLOAT,
  sales_7_d                            FLOAT,
  sales_14_d                           FLOAT,
  sales_30_d                           FLOAT,
  attributed_sales_same_sku_1_d        FLOAT,
  attributed_sales_same_sku_7_d        FLOAT,
  attributed_sales_same_sku_14_d       FLOAT,
  attributed_sales_same_sku_30_d       FLOAT,
  synced_at                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id, profile_id, ad_group_id, date)
);

CREATE TABLE IF NOT EXISTS sp_targeting_keyword_report (
  client_id                            VARCHAR(36)   NOT NULL,
  profile_id                           VARCHAR(36)   NOT NULL,
  campaign_id                          VARCHAR(64)   NOT NULL,
  ad_group_id                          VARCHAR(64)   NOT NULL,
  keyword_id                           VARCHAR(64)   NOT NULL,
  date                                 DATE          NOT NULL,
  -- Targeting metadata
  keyword                              VARCHAR(512),
  keyword_type                         VARCHAR(64),
  match_type                           VARCHAR(32),
  targeting                            VARCHAR(512),
  ad_keyword_status                    VARCHAR(32),
  keyword_bid                          FLOAT,
  -- Campaign context
  campaign_name                        VARCHAR(512),
  campaign_status                      VARCHAR(32),
  campaign_budget_amount               FLOAT,
  campaign_budget_type                 VARCHAR(64),
  campaign_budget_currency_code        VARCHAR(8),
  campaign_bidding_strategy            VARCHAR(64),
  portfolio_id                         VARCHAR(64),
  top_of_search_impression_share       FLOAT,
  ad_group_name                        VARCHAR(512),
  -- Performance
  impressions                          NUMBER,
  clicks                               NUMBER,
  cost                                 FLOAT,
  -- Purchases — all windows
  purchases_1_d                        NUMBER,
  purchases_7_d                        NUMBER,
  purchases_14_d                       NUMBER,
  purchases_30_d                       NUMBER,
  purchases_same_sku_1_d               NUMBER,
  purchases_same_sku_7_d               NUMBER,
  purchases_same_sku_14_d              NUMBER,
  purchases_same_sku_30_d              NUMBER,
  -- Units sold
  units_sold_clicks_1_d                NUMBER,
  units_sold_clicks_7_d                NUMBER,
  units_sold_clicks_14_d               NUMBER,
  units_sold_clicks_30_d               NUMBER,
  units_sold_same_sku_1_d              NUMBER,
  units_sold_same_sku_7_d              NUMBER,
  units_sold_same_sku_14_d             NUMBER,
  units_sold_same_sku_30_d             NUMBER,
  -- Sales
  sales_1_d                            FLOAT,
  sales_7_d                            FLOAT,
  sales_14_d                           FLOAT,
  sales_30_d                           FLOAT,
  attributed_sales_same_sku_1_d        FLOAT,
  attributed_sales_same_sku_7_d        FLOAT,
  attributed_sales_same_sku_14_d       FLOAT,
  attributed_sales_same_sku_30_d       FLOAT,
  sales_other_sku_7_d                  FLOAT,
  units_sold_other_sku_7_d             NUMBER,
  synced_at                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id, profile_id, campaign_id, ad_group_id, keyword_id, date)
);

CREATE TABLE IF NOT EXISTS sp_search_term_report (
  client_id                            VARCHAR(36)   NOT NULL,
  profile_id                           VARCHAR(36)   NOT NULL,
  campaign_id                          VARCHAR(64)   NOT NULL,
  ad_group_id                          VARCHAR(64)   NOT NULL,
  keyword_id                           VARCHAR(64)   NOT NULL,
  search_term                          VARCHAR(512)  NOT NULL,
  date                                 DATE          NOT NULL,
  -- Metadata
  keyword                              VARCHAR(512),
  keyword_type                         VARCHAR(64),
  match_type                           VARCHAR(32),
  targeting                            VARCHAR(512),
  ad_keyword_status                    VARCHAR(32),
  keyword_bid                          FLOAT,
  campaign_name                        VARCHAR(512),
  campaign_status                      VARCHAR(32),
  campaign_budget_amount               FLOAT,
  campaign_budget_type                 VARCHAR(64),
  campaign_budget_currency_code        VARCHAR(8),
  portfolio_id                         VARCHAR(64),
  ad_group_name                        VARCHAR(512),
  -- Performance
  impressions                          NUMBER,
  clicks                               NUMBER,
  cost                                 FLOAT,
  -- Purchases
  purchases_1_d                        NUMBER,
  purchases_7_d                        NUMBER,
  purchases_14_d                       NUMBER,
  purchases_30_d                       NUMBER,
  purchases_same_sku_1_d               NUMBER,
  purchases_same_sku_7_d               NUMBER,
  purchases_same_sku_14_d              NUMBER,
  purchases_same_sku_30_d              NUMBER,
  -- Units
  units_sold_clicks_1_d                NUMBER,
  units_sold_clicks_7_d                NUMBER,
  units_sold_clicks_14_d               NUMBER,
  units_sold_clicks_30_d               NUMBER,
  -- Sales
  sales_1_d                            FLOAT,
  sales_7_d                            FLOAT,
  sales_14_d                           FLOAT,
  sales_30_d                           FLOAT,
  attributed_sales_same_sku_1_d        FLOAT,
  attributed_sales_same_sku_7_d        FLOAT,
  attributed_sales_same_sku_14_d       FLOAT,
  attributed_sales_same_sku_30_d       FLOAT,
  sales_other_sku_7_d                  FLOAT,
  synced_at                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id, profile_id, campaign_id, ad_group_id, keyword_id, search_term, date)
);

CREATE TABLE IF NOT EXISTS sp_advertised_product_report (
  client_id                            VARCHAR(36)   NOT NULL,
  profile_id                           VARCHAR(36)   NOT NULL,
  campaign_id                          VARCHAR(64)   NOT NULL,
  ad_group_id                          VARCHAR(64)   NOT NULL,
  ad_id                                VARCHAR(64)   NOT NULL,
  date                                 DATE          NOT NULL,
  -- Product metadata
  advertised_asin                      VARCHAR(32),
  advertised_sku                       VARCHAR(128),
  -- Campaign context
  campaign_name                        VARCHAR(512),
  campaign_status                      VARCHAR(32),
  campaign_budget_amount               FLOAT,
  campaign_budget_type                 VARCHAR(64),
  campaign_budget_currency_code        VARCHAR(8),
  campaign_bidding_strategy            VARCHAR(64),
  portfolio_id                         VARCHAR(64),
  ad_group_name                        VARCHAR(512),
  -- Performance
  impressions                          NUMBER,
  clicks                               NUMBER,
  cost                                 FLOAT,
  -- Purchases — all windows
  purchases_1_d                        NUMBER,
  purchases_7_d                        NUMBER,
  purchases_14_d                       NUMBER,
  purchases_30_d                       NUMBER,
  purchases_same_sku_1_d               NUMBER,
  purchases_same_sku_7_d               NUMBER,
  purchases_same_sku_14_d              NUMBER,
  purchases_same_sku_30_d              NUMBER,
  -- Units
  units_sold_clicks_1_d                NUMBER,
  units_sold_clicks_7_d                NUMBER,
  units_sold_clicks_14_d               NUMBER,
  units_sold_clicks_30_d               NUMBER,
  units_sold_same_sku_1_d              NUMBER,
  units_sold_same_sku_7_d              NUMBER,
  units_sold_same_sku_14_d             NUMBER,
  units_sold_same_sku_30_d             NUMBER,
  units_sold_other_sku_7_d             NUMBER,
  -- Sales
  sales_1_d                            FLOAT,
  sales_7_d                            FLOAT,
  sales_14_d                           FLOAT,
  sales_30_d                           FLOAT,
  attributed_sales_same_sku_1_d        FLOAT,
  attributed_sales_same_sku_7_d        FLOAT,
  attributed_sales_same_sku_14_d       FLOAT,
  attributed_sales_same_sku_30_d       FLOAT,
  sales_other_sku_7_d                  FLOAT,
  synced_at                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id, profile_id, campaign_id, ad_group_id, ad_id, date)
);

CREATE TABLE IF NOT EXISTS sp_campaign_placement_report (
  client_id                            VARCHAR(36)   NOT NULL,
  profile_id                           VARCHAR(36)   NOT NULL,
  campaign_id                          VARCHAR(64)   NOT NULL,
  placement                            VARCHAR(128)  NOT NULL,
  date                                 DATE          NOT NULL,
  -- Campaign context
  campaign_name                        VARCHAR(512),
  campaign_status                      VARCHAR(32),
  campaign_budget_amount               FLOAT,
  campaign_budget_type                 VARCHAR(64),
  campaign_budget_currency_code        VARCHAR(8),
  top_of_search_impression_share       FLOAT,
  placement_classification             VARCHAR(128),
  -- Performance
  impressions                          NUMBER,
  clicks                               NUMBER,
  cost                                 FLOAT,
  purchases_1_d                        NUMBER,
  purchases_7_d                        NUMBER,
  purchases_14_d                       NUMBER,
  purchases_30_d                       NUMBER,
  units_sold_clicks_1_d                NUMBER,
  units_sold_clicks_7_d                NUMBER,
  units_sold_clicks_14_d               NUMBER,
  units_sold_clicks_30_d               NUMBER,
  sales_1_d                            FLOAT,
  sales_7_d                            FLOAT,
  sales_14_d                           FLOAT,
  sales_30_d                           FLOAT,
  synced_at                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id, profile_id, campaign_id, placement, date)
);

CREATE TABLE IF NOT EXISTS sp_purchased_product_report (
  client_id                            VARCHAR(36)   NOT NULL,
  profile_id                           VARCHAR(36)   NOT NULL,
  campaign_id                          VARCHAR(64)   NOT NULL,
  ad_group_id                          VARCHAR(64),
  keyword_id                           VARCHAR(64),
  advertised_asin                      VARCHAR(32),
  purchased_asin                       VARCHAR(32)   NOT NULL,
  date                                 DATE          NOT NULL,
  advertised_sku                       VARCHAR(128),
  keyword_type                         VARCHAR(64),
  keyword                              VARCHAR(512),
  match_type                           VARCHAR(32),
  campaign_budget_currency_code        VARCHAR(8),
  purchases_1_d                        NUMBER,
  purchases_7_d                        NUMBER,
  purchases_14_d                       NUMBER,
  purchases_30_d                       NUMBER,
  purchases_other_sku_1_d              NUMBER,
  purchases_other_sku_7_d              NUMBER,
  purchases_other_sku_14_d             NUMBER,
  purchases_other_sku_30_d             NUMBER,
  units_sold_clicks_1_d                NUMBER,
  units_sold_clicks_7_d                NUMBER,
  units_sold_clicks_14_d               NUMBER,
  units_sold_clicks_30_d               NUMBER,
  units_sold_other_sku_1_d             NUMBER,
  units_sold_other_sku_7_d             NUMBER,
  units_sold_other_sku_14_d            NUMBER,
  units_sold_other_sku_30_d            NUMBER,
  sales_1_d                            FLOAT,
  sales_7_d                            FLOAT,
  sales_14_d                           FLOAT,
  sales_30_d                           FLOAT,
  sales_other_sku_1_d                  FLOAT,
  sales_other_sku_7_d                  FLOAT,
  sales_other_sku_14_d                 FLOAT,
  sales_other_sku_30_d                 FLOAT,
  synced_at                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id, profile_id, campaign_id, ad_group_id, keyword_id, advertised_asin, purchased_asin, date)
);

-- ============================================================
-- SPONSORED BRANDS
-- ============================================================

CREATE TABLE IF NOT EXISTS sb_campaign_report (
  client_id                            VARCHAR(36)   NOT NULL,
  profile_id                           VARCHAR(36)   NOT NULL,
  campaign_id                          VARCHAR(64)   NOT NULL,
  report_date                          DATE          NOT NULL,
  campaign_name                        VARCHAR(512),
  campaign_status                      VARCHAR(32),
  campaign_budget_amount               FLOAT,
  campaign_budget_type                 VARCHAR(64),
  campaign_budget_currency_code        VARCHAR(8),
  cost_type                            VARCHAR(32),
  impressions                          NUMBER,
  clicks                               NUMBER,
  cost                                 FLOAT,
  purchases                            NUMBER,
  purchases_clicks                     NUMBER,
  purchases_promoted                   NUMBER,
  sales                                FLOAT,
  sales_clicks                         FLOAT,
  sales_promoted                       FLOAT,
  units_sold                           NUMBER,
  units_sold_clicks                    NUMBER,
  new_to_brand_purchases               NUMBER,
  new_to_brand_purchases_clicks        NUMBER,
  new_to_brand_purchases_percentage    FLOAT,
  new_to_brand_purchases_rate          FLOAT,
  new_to_brand_sales                   FLOAT,
  new_to_brand_sales_clicks            FLOAT,
  new_to_brand_sales_percentage        FLOAT,
  new_to_brand_units_sold              NUMBER,
  new_to_brand_units_sold_clicks       NUMBER,
  new_to_brand_units_sold_percentage   FLOAT,
  new_to_brand_detail_page_views       NUMBER,
  new_to_brand_detail_page_views_clicks NUMBER,
  new_to_brand_detail_page_view_rate   FLOAT,
  new_to_brand_e_c_p_detail_page_view  FLOAT,
  detail_page_views                    NUMBER,
  detail_page_views_clicks             NUMBER,
  add_to_cart                          NUMBER,
  add_to_cart_clicks                   NUMBER,
  add_to_cart_rate                     FLOAT,
  branded_searches                     NUMBER,
  branded_searches_clicks              NUMBER,
  brand_store_page_view                NUMBER,
  top_of_search_impression_share       FLOAT,
  video_5_second_view_rate             FLOAT,
  video_5_second_views                 NUMBER,
  video_complete_views                 NUMBER,
  video_first_quartile_views           NUMBER,
  video_midpoint_views                 NUMBER,
  video_third_quartile_views           NUMBER,
  video_unmutes                        NUMBER,
  viewability_rate                     FLOAT,
  viewable_impressions                 NUMBER,
  view_click_through_rate              FLOAT,
  kindle_edition_normalized_pages_read_14_d       NUMBER,
  kindle_edition_normalized_pages_royalties_14_d  FLOAT,
  synced_at                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id, profile_id, campaign_id, report_date)
);

CREATE TABLE IF NOT EXISTS sb_keyword_report (
  client_id                            VARCHAR(36)   NOT NULL,
  profile_id                           VARCHAR(36)   NOT NULL,
  keyword_id                           VARCHAR(64)   NOT NULL,
  report_date                          DATE          NOT NULL,
  campaign_id                          VARCHAR(64),
  campaign_name                        VARCHAR(512),
  campaign_status                      VARCHAR(32),
  campaign_budget_amount               FLOAT,
  campaign_budget_type                 VARCHAR(64),
  campaign_budget_currency_code        VARCHAR(8),
  ad_group_id                          VARCHAR(64),
  ad_group_name                        VARCHAR(512),
  keyword_text                         VARCHAR(512),
  keyword_type                         VARCHAR(64),
  match_type                           VARCHAR(32),
  keyword_bid                          FLOAT,
  ad_keyword_status                    VARCHAR(32),
  targeting_expression                 VARCHAR(1024),
  targeting_id                         VARCHAR(64),
  targeting_text                       VARCHAR(512),
  targeting_type                       VARCHAR(64),
  top_of_search_impression_share       FLOAT,
  impressions                          NUMBER,
  clicks                               NUMBER,
  cost                                 FLOAT,
  cost_type                            VARCHAR(32),
  purchases                            NUMBER,
  purchases_clicks                     NUMBER,
  purchases_promoted                   NUMBER,
  sales                                FLOAT,
  sales_clicks                         FLOAT,
  sales_promoted                       FLOAT,
  units_sold                           NUMBER,
  new_to_brand_purchases               NUMBER,
  new_to_brand_purchases_clicks        NUMBER,
  new_to_brand_purchases_percentage    FLOAT,
  new_to_brand_purchases_rate          FLOAT,
  new_to_brand_sales                   FLOAT,
  new_to_brand_sales_clicks            FLOAT,
  new_to_brand_sales_percentage        FLOAT,
  new_to_brand_units_sold              NUMBER,
  new_to_brand_units_sold_clicks       NUMBER,
  new_to_brand_units_sold_percentage   FLOAT,
  new_to_brand_detail_page_views       NUMBER,
  new_to_brand_detail_page_views_clicks NUMBER,
  new_to_brand_detail_page_view_rate   FLOAT,
  new_to_brand_e_c_p_detail_page_view  FLOAT,
  detail_page_views                    NUMBER,
  detail_page_views_clicks             NUMBER,
  add_to_cart                          NUMBER,
  add_to_cart_clicks                   NUMBER,
  branded_searches                     NUMBER,
  branded_searches_clicks              NUMBER,
  synced_at                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id, profile_id, keyword_id, report_date)
);

CREATE TABLE IF NOT EXISTS sb_search_term_report (
  client_id                            VARCHAR(36)   NOT NULL,
  profile_id                           VARCHAR(36)   NOT NULL,
  keyword_id                           VARCHAR(64)   NOT NULL,
  search_term                          VARCHAR(512)  NOT NULL,
  report_date                          DATE          NOT NULL,
  campaign_id                          VARCHAR(64),
  campaign_name                        VARCHAR(512),
  campaign_status                      VARCHAR(32),
  campaign_budget_amount               FLOAT,
  campaign_budget_type                 VARCHAR(64),
  campaign_budget_currency_code        VARCHAR(8),
  ad_group_id                          VARCHAR(64),
  ad_group_name                        VARCHAR(512),
  keyword_text                         VARCHAR(512),
  match_type                           VARCHAR(32),
  keyword_bid                          FLOAT,
  cost_type                            VARCHAR(32),
  impressions                          NUMBER,
  clicks                               NUMBER,
  cost                                 FLOAT,
  purchases                            NUMBER,
  purchases_clicks                     NUMBER,
  sales                                FLOAT,
  sales_clicks                         FLOAT,
  units_sold                           NUMBER,
  video_5_second_view_rate             FLOAT,
  video_5_second_views                 NUMBER,
  video_complete_views                 NUMBER,
  video_first_quartile_views           NUMBER,
  video_midpoint_views                 NUMBER,
  video_third_quartile_views           NUMBER,
  video_unmutes                        NUMBER,
  viewability_rate                     FLOAT,
  viewable_impressions                 NUMBER,
  view_click_through_rate              FLOAT,
  kindle_edition_normalized_pages_read_14_d       NUMBER,
  kindle_edition_normalized_pages_royalties_14_d  FLOAT,
  synced_at                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id, profile_id, keyword_id, search_term, report_date)
);

CREATE TABLE IF NOT EXISTS sb_target_report (
  client_id                            VARCHAR(36)   NOT NULL,
  profile_id                           VARCHAR(36)   NOT NULL,
  target_id                            VARCHAR(64)   NOT NULL,
  report_date                          DATE          NOT NULL,
  campaign_id                          VARCHAR(64),
  campaign_name                        VARCHAR(512),
  campaign_status                      VARCHAR(32),
  campaign_budget_amount               FLOAT,
  campaign_budget_type                 VARCHAR(64),
  campaign_budget_currency_code        VARCHAR(8),
  ad_group_id                          VARCHAR(64),
  ad_group_name                        VARCHAR(512),
  targeting_expression                 VARCHAR(1024),
  targeting_text                       VARCHAR(512),
  targeting_type                       VARCHAR(64),
  top_of_search_impression_share       FLOAT,
  cost_type                            VARCHAR(32),
  impressions                          NUMBER,
  clicks                               NUMBER,
  cost                                 FLOAT,
  purchases                            NUMBER,
  purchases_clicks                     NUMBER,
  sales                                FLOAT,
  sales_clicks                         FLOAT,
  units_sold                           NUMBER,
  new_to_brand_purchases               NUMBER,
  new_to_brand_purchases_clicks        NUMBER,
  new_to_brand_sales                   FLOAT,
  new_to_brand_sales_clicks            FLOAT,
  new_to_brand_units_sold              NUMBER,
  new_to_brand_units_sold_clicks       NUMBER,
  synced_at                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id, profile_id, target_id, report_date)
);

CREATE TABLE IF NOT EXISTS sb_placement_report (
  client_id                            VARCHAR(36)   NOT NULL,
  profile_id                           VARCHAR(36)   NOT NULL,
  campaign_id                          VARCHAR(64)   NOT NULL,
  placement                            VARCHAR(128)  NOT NULL,
  report_date                          DATE          NOT NULL,
  campaign_name                        VARCHAR(512),
  campaign_status                      VARCHAR(32),
  campaign_budget_amount               FLOAT,
  campaign_budget_type                 VARCHAR(64),
  campaign_budget_currency_code        VARCHAR(8),
  placement_classification             VARCHAR(128),
  cost_type                            VARCHAR(32),
  impressions                          NUMBER,
  clicks                               NUMBER,
  cost                                 FLOAT,
  purchases                            NUMBER,
  purchases_clicks                     NUMBER,
  purchases_promoted                   NUMBER,
  sales                                FLOAT,
  sales_clicks                         FLOAT,
  sales_promoted                       FLOAT,
  units_sold                           NUMBER,
  units_sold_clicks                    NUMBER,
  new_to_brand_purchases               NUMBER,
  new_to_brand_purchases_clicks        NUMBER,
  new_to_brand_purchases_percentage    FLOAT,
  new_to_brand_sales                   FLOAT,
  new_to_brand_sales_clicks            FLOAT,
  new_to_brand_sales_percentage        FLOAT,
  new_to_brand_units_sold              NUMBER,
  new_to_brand_units_sold_clicks       NUMBER,
  new_to_brand_units_sold_percentage   FLOAT,
  new_to_brand_detail_page_views       NUMBER,
  new_to_brand_detail_page_views_clicks NUMBER,
  new_to_brand_detail_page_view_rate   FLOAT,
  new_to_brand_e_c_p_detail_page_view  FLOAT,
  detail_page_views                    NUMBER,
  detail_page_views_clicks             NUMBER,
  add_to_cart                          NUMBER,
  add_to_cart_clicks                   NUMBER,
  video_5_second_views                 NUMBER,
  video_complete_views                 NUMBER,
  video_first_quartile_views           NUMBER,
  video_midpoint_views                 NUMBER,
  video_third_quartile_views           NUMBER,
  video_unmutes                        NUMBER,
  viewability_rate                     FLOAT,
  viewable_impressions                 NUMBER,
  synced_at                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id, profile_id, campaign_id, placement, report_date)
);

-- ============================================================
-- SPONSORED DISPLAY
-- ============================================================

CREATE TABLE IF NOT EXISTS sd_campaign_report (
  client_id                            VARCHAR(36)   NOT NULL,
  profile_id                           VARCHAR(36)   NOT NULL,
  campaign_id                          VARCHAR(64)   NOT NULL,
  date                                 DATE          NOT NULL,
  campaign_name                        VARCHAR(512),
  campaign_status                      VARCHAR(32),
  campaign_budget_amount               FLOAT,
  campaign_budget_currency_code        VARCHAR(8),
  cost_type                            VARCHAR(32),
  impressions                          NUMBER,
  impressions_views                    NUMBER,
  clicks                               NUMBER,
  cost                                 FLOAT,
  purchases                            NUMBER,
  purchases_clicks                     NUMBER,
  purchases_promoted_clicks            NUMBER,
  sales                                FLOAT,
  sales_clicks                         FLOAT,
  sales_promoted_clicks                FLOAT,
  units_sold                           NUMBER,
  units_sold_clicks                    NUMBER,
  detail_page_views                    NUMBER,
  detail_page_views_clicks             NUMBER,
  add_to_cart                          NUMBER,
  add_to_cart_clicks                   NUMBER,
  add_to_cart_views                    NUMBER,
  add_to_cart_rate                     FLOAT,
  branded_searches                     NUMBER,
  branded_searches_clicks              NUMBER,
  branded_searches_views               NUMBER,
  branded_search_rate                  FLOAT,
  new_to_brand_purchases               NUMBER,
  new_to_brand_purchases_clicks        NUMBER,
  new_to_brand_sales                   FLOAT,
  new_to_brand_sales_clicks            FLOAT,
  new_to_brand_units_sold              NUMBER,
  new_to_brand_units_sold_clicks       NUMBER,
  new_to_brand_detail_page_views       NUMBER,
  new_to_brand_detail_page_view_clicks NUMBER,
  new_to_brand_detail_page_view_rate   FLOAT,
  new_to_brand_detail_page_view_views  NUMBER,
  new_to_brand_e_c_p_detail_page_view  FLOAT,
  cumulative_reach                     NUMBER,
  impressions_frequency_average        FLOAT,
  video_complete_views                 NUMBER,
  video_first_quartile_views           NUMBER,
  video_midpoint_views                 NUMBER,
  video_third_quartile_views           NUMBER,
  video_unmutes                        NUMBER,
  viewability_rate                     FLOAT,
  view_click_through_rate              FLOAT,
  e_c_p_brand_search                   FLOAT,
  long_term_sales                      FLOAT,
  long_term_r_o_a_s                    FLOAT,
  synced_at                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id, profile_id, campaign_id, date)
);

CREATE TABLE IF NOT EXISTS sd_ad_group_report (
  client_id                            VARCHAR(36)   NOT NULL,
  profile_id                           VARCHAR(36)   NOT NULL,
  ad_group_id                          VARCHAR(64)   NOT NULL,
  date                                 DATE          NOT NULL,
  ad_group_name                        VARCHAR(512),
  campaign_id                          VARCHAR(64),
  bid_optimization                     VARCHAR(64),
  impressions                          NUMBER,
  impressions_views                    NUMBER,
  clicks                               NUMBER,
  cost                                 FLOAT,
  purchases                            NUMBER,
  purchases_clicks                     NUMBER,
  purchases_promoted_clicks            NUMBER,
  sales                                FLOAT,
  sales_clicks                         FLOAT,
  sales_promoted_clicks                FLOAT,
  units_sold                           NUMBER,
  units_sold_clicks                    NUMBER,
  detail_page_views                    NUMBER,
  detail_page_views_clicks             NUMBER,
  add_to_cart                          NUMBER,
  add_to_cart_clicks                   NUMBER,
  add_to_cart_views                    NUMBER,
  branded_searches                     NUMBER,
  branded_searches_clicks              NUMBER,
  branded_searches_views               NUMBER,
  new_to_brand_purchases               NUMBER,
  new_to_brand_purchases_clicks        NUMBER,
  new_to_brand_sales                   FLOAT,
  new_to_brand_sales_clicks            FLOAT,
  new_to_brand_units_sold              NUMBER,
  new_to_brand_units_sold_clicks       NUMBER,
  new_to_brand_detail_page_views       NUMBER,
  new_to_brand_detail_page_view_clicks NUMBER,
  new_to_brand_detail_page_view_rate   FLOAT,
  new_to_brand_detail_page_view_views  NUMBER,
  new_to_brand_e_c_p_detail_page_view  FLOAT,
  cumulative_reach                     NUMBER,
  impressions_frequency_average        FLOAT,
  video_complete_views                 NUMBER,
  video_first_quartile_views           NUMBER,
  video_midpoint_views                 NUMBER,
  video_third_quartile_views           NUMBER,
  video_unmutes                        NUMBER,
  viewability_rate                     FLOAT,
  view_click_through_rate              FLOAT,
  e_c_p_brand_search                   FLOAT,
  synced_at                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id, profile_id, ad_group_id, date)
);

CREATE TABLE IF NOT EXISTS sd_target_report (
  client_id                            VARCHAR(36)   NOT NULL,
  profile_id                           VARCHAR(36)   NOT NULL,
  ad_group_id                          VARCHAR(64)   NOT NULL,
  campaign_id                          VARCHAR(64)   NOT NULL,
  targeting_id                         VARCHAR(64)   NOT NULL,
  date                                 DATE          NOT NULL,
  ad_group_name                        VARCHAR(512),
  campaign_name                        VARCHAR(512),
  campaign_budget_currency_code        VARCHAR(8),
  targeting_expression                 VARCHAR(1024),
  targeting_text                       VARCHAR(512),
  impressions                          NUMBER,
  impressions_views                    NUMBER,
  clicks                               NUMBER,
  cost                                 FLOAT,
  purchases                            NUMBER,
  purchases_clicks                     NUMBER,
  purchases_promoted_clicks            NUMBER,
  sales                                FLOAT,
  sales_clicks                         FLOAT,
  sales_promoted_clicks                FLOAT,
  units_sold                           NUMBER,
  units_sold_clicks                    NUMBER,
  detail_page_views                    NUMBER,
  detail_page_views_clicks             NUMBER,
  add_to_cart                          NUMBER,
  add_to_cart_clicks                   NUMBER,
  add_to_cart_views                    NUMBER,
  branded_searches                     NUMBER,
  branded_searches_clicks              NUMBER,
  branded_searches_views               NUMBER,
  branded_search_rate                  FLOAT,
  new_to_brand_purchases               NUMBER,
  new_to_brand_purchases_clicks        NUMBER,
  new_to_brand_sales                   FLOAT,
  new_to_brand_sales_clicks            FLOAT,
  new_to_brand_units_sold              NUMBER,
  new_to_brand_units_sold_clicks       NUMBER,
  new_to_brand_detail_page_views       NUMBER,
  new_to_brand_detail_page_view_clicks NUMBER,
  new_to_brand_detail_page_view_rate   FLOAT,
  new_to_brand_detail_page_view_views  NUMBER,
  new_to_brand_e_c_p_detail_page_view  FLOAT,
  video_complete_views                 NUMBER,
  video_first_quartile_views           NUMBER,
  video_midpoint_views                 NUMBER,
  video_third_quartile_views           NUMBER,
  video_unmutes                        NUMBER,
  viewability_rate                     FLOAT,
  view_click_through_rate              FLOAT,
  e_c_p_brand_search                   FLOAT,
  synced_at                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id, profile_id, ad_group_id, campaign_id, targeting_id, date)
);

CREATE TABLE IF NOT EXISTS sd_product_ad_report (
  client_id                            VARCHAR(36)   NOT NULL,
  profile_id                           VARCHAR(36)   NOT NULL,
  ad_id                                VARCHAR(64)   NOT NULL,
  date                                 DATE          NOT NULL,
  ad_group_id                          VARCHAR(64),
  ad_group_name                        VARCHAR(512),
  campaign_id                          VARCHAR(64),
  campaign_name                        VARCHAR(512),
  campaign_budget_currency_code        VARCHAR(8),
  promoted_asin                        VARCHAR(32),
  promoted_sku                         VARCHAR(128),
  bid_optimization                     VARCHAR(64),
  impressions                          NUMBER,
  impressions_views                    NUMBER,
  impressions_frequency_average        FLOAT,
  clicks                               NUMBER,
  cost                                 FLOAT,
  purchases                            NUMBER,
  purchases_clicks                     NUMBER,
  purchases_promoted_clicks            NUMBER,
  sales                                FLOAT,
  sales_clicks                         FLOAT,
  sales_promoted_clicks                FLOAT,
  units_sold                           NUMBER,
  units_sold_clicks                    NUMBER,
  detail_page_views                    NUMBER,
  detail_page_views_clicks             NUMBER,
  add_to_cart                          NUMBER,
  add_to_cart_clicks                   NUMBER,
  add_to_cart_views                    NUMBER,
  branded_searches                     NUMBER,
  branded_searches_clicks              NUMBER,
  branded_searches_views               NUMBER,
  branded_search_rate                  FLOAT,
  new_to_brand_purchases               NUMBER,
  new_to_brand_purchases_clicks        NUMBER,
  new_to_brand_sales                   FLOAT,
  new_to_brand_sales_clicks            FLOAT,
  new_to_brand_units_sold              NUMBER,
  new_to_brand_units_sold_clicks       NUMBER,
  new_to_brand_detail_page_views       NUMBER,
  new_to_brand_detail_page_view_clicks NUMBER,
  new_to_brand_detail_page_view_rate   FLOAT,
  new_to_brand_detail_page_view_views  NUMBER,
  new_to_brand_e_c_p_detail_page_view  FLOAT,
  cumulative_reach                     NUMBER,
  video_complete_views                 NUMBER,
  video_first_quartile_views           NUMBER,
  video_midpoint_views                 NUMBER,
  video_third_quartile_views           NUMBER,
  video_unmutes                        NUMBER,
  viewability_rate                     FLOAT,
  view_click_through_rate              FLOAT,
  e_c_p_brand_search                   FLOAT,
  synced_at                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id, profile_id, ad_id, date)
);

-- ============================================================
-- DSP
-- ============================================================

CREATE TABLE IF NOT EXISTS dsp_campaign_report (
  advertiser_id                        VARCHAR(64)   NOT NULL,
  profile_id                           VARCHAR(36)   NOT NULL,
  client_id                            VARCHAR(36),
  date                                 DATE          NOT NULL,
  order_id                             VARCHAR(64),
  order_name                           VARCHAR(512),
  impressions                          NUMBER,
  clicks                               NUMBER,
  total_cost                           FLOAT,
  detail_page_views                    NUMBER,
  detail_page_view_clicks              NUMBER,
  add_to_cart                          NUMBER,
  add_to_cart_clicks                   NUMBER,
  purchases                            NUMBER,
  purchases_clicks                     NUMBER,
  total_purchases                      NUMBER,
  total_purchases_clicks               NUMBER,
  sales                                FLOAT,
  total_sales                          FLOAT,
  new_to_brand_purchases               NUMBER,
  new_to_brand_purchases_clicks        NUMBER,
  new_to_brand_product_sales           FLOAT,
  viewable_impressions                 NUMBER,
  viewability_rate                     FLOAT,
  advertiser_name                      VARCHAR(512),
  entity_id                            VARCHAR(64),
  order_budget                         FLOAT,
  order_start_date                     DATE,
  order_end_date                       DATE,
  order_currency                       VARCHAR(8),
  synced_at                            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (advertiser_id, profile_id, date, order_id)
);

-- ============================================================
-- ENTITY / HISTORY TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS sp_campaign_history (
  id                    TEXT          NOT NULL,
  last_updated_date     TIMESTAMP_TZ  NOT NULL,
  serving_status        TEXT,
  creation_date         TIMESTAMP_TZ,
  portfolio_id          TEXT,
  profile_id            NUMBER,
  name                  TEXT,
  targeting_type        TEXT,
  state                 TEXT,
  bidding_strategy      TEXT,
  start_date            DATE,
  end_date              DATE,
  budget_type           TEXT,
  budget                FLOAT,
  effective_budget      FLOAT,
  synced_at             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id, last_updated_date)
);

CREATE TABLE IF NOT EXISTS sp_ad_group_history (
  id                    TEXT          NOT NULL,
  last_updated_date     TIMESTAMP_TZ  NOT NULL,
  serving_status        TEXT,
  creation_date         TIMESTAMP_TZ,
  campaign_id           TEXT,
  name                  TEXT,
  default_bid           FLOAT,
  state                 TEXT,
  synced_at             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id, last_updated_date)
);

CREATE TABLE IF NOT EXISTS sp_keyword_history (
  id                    TEXT          NOT NULL,
  last_updated_date     TIMESTAMP_TZ  NOT NULL,
  campaign_id           TEXT,
  keyword_text          TEXT,
  state                 TEXT,
  match_type            TEXT,
  serving_status        TEXT,
  creation_date         TIMESTAMP_TZ,
  ad_group_id           TEXT,
  native_language_keyword TEXT,
  native_language_locale  TEXT,
  bid                   FLOAT,
  synced_at             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id, last_updated_date)
);

CREATE TABLE IF NOT EXISTS sp_product_ad_history (
  id                    TEXT          NOT NULL,
  last_updated_date     TIMESTAMP_TZ  NOT NULL,
  campaign_id           TEXT,
  ad_group_id           TEXT,
  custom_text           TEXT,
  sku                   TEXT,
  asin                  TEXT,
  state                 TEXT,
  serving_status        TEXT,
  creation_date         TIMESTAMP_TZ,
  synced_at             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id, last_updated_date)
);

CREATE TABLE IF NOT EXISTS sp_portfolio_history (
  id                    NUMBER        NOT NULL,
  last_updated_date     TIMESTAMP_TZ  NOT NULL,
  profile_id            NUMBER,
  name                  TEXT,
  in_budget             BOOLEAN,
  state                 TEXT,
  serving_status        TEXT,
  creation_date         TIMESTAMP_TZ,
  budget_amount         FLOAT,
  budget_currency_code  TEXT,
  budget_policy         TEXT,
  budget_start_date     DATE,
  budget_end_date       DATE,
  synced_at             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id, last_updated_date)
);

CREATE TABLE IF NOT EXISTS sb_campaign_history (
  id                    TEXT          NOT NULL,
  last_update_date      TIMESTAMP_TZ  NOT NULL,
  brand_entity_id       TEXT,
  budget                FLOAT,
  budget_type           TEXT,
  cost_type             TEXT,
  creation_date         TIMESTAMP_TZ,
  serving_status        TEXT,
  end_date              DATE,
  goal                  TEXT,
  name                  TEXT,
  profile_id            NUMBER,
  portfolio_id          TEXT,
  start_date            DATE,
  state                 TEXT,
  synced_at             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id, last_update_date)
);

CREATE TABLE IF NOT EXISTS sb_keyword (
  id                    TEXT          NOT NULL PRIMARY KEY,
  ad_group_id           TEXT,
  campaign_id           TEXT,
  keyword_text          TEXT,
  native_language_keyword TEXT,
  match_type            TEXT,
  state                 TEXT,
  bid                   FLOAT,
  synced_at             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sd_campaign_history (
  id                    TEXT          NOT NULL,
  last_updated_date     TIMESTAMP_TZ  NOT NULL,
  profile_id            NUMBER,
  portfolio_id          TEXT,
  name                  TEXT,
  tactic                TEXT,
  budget_type           TEXT,
  budget                FLOAT,
  start_date            DATE,
  end_date              DATE,
  state                 TEXT,
  serving_status        TEXT,
  cost_type             TEXT,
  creation_date         TIMESTAMP_TZ,
  synced_at             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id, last_updated_date)
);
